### ISSUE TITLE
Graph of variance explained by extracted components  

### ISSUE THREAD

**Issue by joshhartshorne** [sdimi/handwritten-digits-recognition#1]
Hi - just looking at the code and graph, am I correct in assuming that 98% of the variance is explained by the first 10 principal components?

**Comment by sdimi** [comment]
Hey, I know this graph might be misleading. It is not cumulative, so you'd better do this instead:

Let's say you want to keep 5 components of a dataset

```python
pca = PCA(n_components=5)
X_transformed = pca.fit_transform(data)
print ("Explained variance:", pca.explained_variance_ratio_.cumsum())
```




which is going to print the variance explained by every component you remove 

`Explained variance: [ 0.32047581  0.59549787  0.80178824  0.932976    1.        ]`

**Comment by joshhartshorne** [comment]
Thanks, very helpful.
